--- 
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: springsql-hpa
  namespace: testfinal
spec: 
  targetCPUUtilizationPercentage: 50
  minReplicas: 1
  maxReplicas: 20
  scaleTargetRef:
    name: springsql
    kind: Deployment
    apiVersion: apps/v1
