---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-pods
  namespace: testfinal
rules:
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["get", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-pods
  namespace: testfinal
subjects:
  - apiGroup: ""
    kind: User
    name: winner
roleRef:
    apiGroup: ""
    kind: Role
    name: role-pods
